version: "3"

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
  mongo:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"